### ISSUE TITLE
HTML&CSS Kata: Todo App

### ISSUE THREAD

**Issue by codingbootcampseu** [BringsCoding/bootcamp-schedule#32]
Create the HTML and CSS for a todo app.

The app will include the following features
- [ ] Add new todo using an input and a button
- [ ] A list of all todos
- [ ] Todos can be marked as complete
- [ ] Todos can be filtered (open, done, all)
- [ ] Done todos can be removed using a button

To give you an impression of the features here is a [minimal unstyled todo app](https://bootcamp-todo-app.stackblitz.io/).

This kata is a preparation for the Todo App JS kata which will mainly focus on functionality. This is the chance to prepare the HTML and CSS in advance.
