### ISSUE TITLE
Backend: Use Todo API

### ISSUE THREAD

**Issue by codingbootcampseu** [BringsCoding/bootcamp-schedule#87]
You will now install a local node based API on your machine and use it with your Todo App.

**Setup of Todo API**

- [x] Go to the [Todo API repository](https://github.com/coding-bootcamps-eu/todo-api) and follow the instructions to install it
- [x] Use [Curl](https://linuxize.com/post/curl-rest-api/) or [Postman](https://www.postman.com/) to study the Todo API

**Modify your Todo App**

- [ ] Modify your Todo App to now use the Todo API
  - [ ] Load Todos from using a `GET` request
  - [ ] Add new todos using a `POST` request
  - [ ] Delete todos using a `DELETE` http request
  - [ ] Update todos (when changing the done state) using a `PUT` http request 

> You can use a separate branch for that if you want
